generic-service:
  ingress:
    host: feature-toggles.hmpps.service.justice.gov.uk

  env:
    FLIPT_CONFIG_FILE: /etc/flipt/config/prod.yml

generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
