generic-service:
  replicaCount: 2

  ingress:
    host: feature-toggles-dev.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: balanced
      nginx.ingress.kubernetes.io/session-cookie-name: FLIPT_AFFINITY
      nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
      nginx.ingress.kubernetes.io/session-cookie-samesite: Strict
      nginx.ingress.kubernetes.io/session-cookie-secure: "true"

  scheduledDowntime:
    # Startup slightly earlier and shutdown slightly later than other services
    startup: '0 6 * * 1-5'    # 6:00am Monday-Friday
    shutdown: '30 22 * * 1-5' # 10:30pm Monday-Friday
    enabled: true

  env:
    FLIPT_CONFIG_FILE: /etc/flipt/config/dev.yml

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
  businessHoursOnly: true
