generic-service:
  ingress:
    host: feature-toggles-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    # Startup slightly earlier and shutdown slightly later than other services
    startup: '0 6 * * 1-5'    # 6:00am Monday-Friday
    shutdown: '30 22 * * 1-5' # 10:30pm Monday-Friday
    enabled: true

  env:
    FLIPT_AUTHENTICATION_SESSION_DOMAIN: feature-toggles-preprod.hmpps.service.justice.gov.uk
    FLIPT_AUTHENTICATION_METHODS_GITHUB_REDIRECT_ADDRESS: https://feature-toggles-preprod.hmpps.service.justice.gov.uk

fliptEnvironment:
  name: "preprod"
  displayName: "Pre-Production"
  directory: "flags/preprod"
  fetchPolicy: "lenient"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
  businessHoursOnly: true
